### ISSUE TITLE
HTML DISPLAY CORRECTION

### ISSUE THREAD

**Issue by RushilVerma** [Tech-Cravers/Book_Trader_nodejs#2]
many of html pages are not displaying personalised content please see to that its configured correctly

**Comment by Aryan4786** [comment]
Bhai kya likh ta rehta hain

**Comment by RushilVerma** [comment]
bhai tune iss repo ko clone karke check kiya jo maine bola tha

**Comment by Aryan4786** [comment]
Bhai net khatam ho gaya tha toh kal subha clone karunga

**Comment by RushilVerma** [comment]
Switch to IDEA broh

**Comment by Aryan4786** [comment]
Haab 😅😅

**Comment by RushilVerma** [comment]
Done
